services:
  thaipq-docker:
    image: arirator120/thaipq-docker
    container_name: thaipq-docker
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        user: bw
        uid: 1000
    restart: always
    ports:
      - 9090:80
    volumes:
      - "./:/var/www/html"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: web_source
      DB_USERNAME: root
      DB_PASSWORD: 
    networks:
      - thaipq-docker-net

networks:
  thaipq-docker-net:
    driver: bridge